### Connection check
GET http://localhost:3001/

### Get All tasks
GET http://localhost:3002/api/tasks

### Get important Tasks

GET http://localhost:3001/api/tasks/filter/important

### Get private Tasks

GET http://localhost:3001/api/tasks/filter/private


### Get public Tasks

GET http://localhost:3001/api/tasks/filter/public

### Get Task with a given id

GET http://localhost:3001/api/tasks/5


### Insert a new task to the DB

POST http://localhost:3001/api/tasks
Content-Type: application/json

{ "description": "Testashvili perfavore 2", "important": 1,"private": 1, "deadline":"2021-05-25 15:00" , "completed":0, "user":1 }

### Update parameters of an existing task

PUT http://localhost:3001/api/tasks/update/12
Content-Type: application/json

{ "description": "Make a reservation for the study room 2R", "important": 0,"private": 0, "deadline":"2021-05-19 16:00" , "completed":1, "user":1 }


### Update task's status to completed
PUT http://localhost:3001/api/tasks/update/completed/9

### Update task's status to uncompleted
PUT http://localhost:3001/api/tasks/update/uncompleted/8

### Delete existing task with a given id
DELETE http://localhost:3001/api/tasks/delete/15






